# docker-compose.override.yml

services:

  spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_MASTER_WEBUI_PORT=8081
      - SPARK_CLASSPATH=/usr/local/airflow/jars/postgresql-42.7.1.jar
      - SPARK_DRIVER_CLASSPATH=/usr/local/airflow/jars/postgresql-42.7.1.jar
      - SPARK_EXECUTOR_CLASSPATH=/usr/local/airflow/jars/postgresql-42.7.1.jar
    ports:
      - "8081:8081"
      - "7077:7077"
    volumes:
      - spark-data:/bitnami
      - ./include:/usr/local/airflow/include
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
      - ./jars:/usr/local/airflow/jars
    networks:
      - airflow

  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_CLASSPATH=/usr/local/airflow/jars/postgresql-42.7.1.jar
      - SPARK_DRIVER_CLASSPATH=/usr/local/airflow/jars/postgresql-42.7.1.jar
      - SPARK_EXECUTOR_CLASSPATH=/usr/local/airflow/jars/postgresql-42.7.1.jar
    volumes:
      - ./include:/usr/local/airflow/include
      - spark-data:/bitnami
      - ./apps:/opt/spark-apps
      - ./jars:/usr/local/airflow/jars
      - ./data:/opt/spark-data
    depends_on:
      - spark-master
    networks:
      - airflow

volumes:
  spark-data: