######################################################################
# # # # # # DECOMMISSIONED UNDER MM-170 AND MIGRATED TO PROD # # # # #
######################################################################

# FROM apache/superset:latest

# USER root

# RUN pip install psycopg2-binary

# USER superset
