# docker-compose.override.yml

services:

  spark-master:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_MASTER_WEBUI_PORT=8081
      - SPARK_CLASSPATH=/usr/local/airflow/jars/postgresql-42.7.1.jar
      - SPARK_DRIVER_CLASSPATH=/usr/local/airflow/jars/postgresql-42.7.1.jar
      - SPARK_EXECUTOR_CLASSPATH=/usr/local/airflow/jars/postgresql-42.7.1.jar
    ports:
      - "8081:8081"
      - "7077:7077"
    volumes:
      - spark-data:/bitnami
      - ./prod_dags:/usr/local/airflow/prod_dags
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
      - ./jars:/usr/local/airflow/jars
    networks:
      - airflow

  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_CLASSPATH=/usr/local/airflow/jars/postgresql-42.7.1.jar
      - SPARK_DRIVER_CLASSPATH=/usr/local/airflow/jars/postgresql-42.7.1.jar
      - SPARK_EXECUTOR_CLASSPATH=/usr/local/airflow/jars/postgresql-42.7.1.jar
    volumes:
      - ./prod_dags:/usr/local/airflow/prod_dags
      - spark-data:/bitnami
      - ./apps:/opt/spark-apps
      - ./jars:/usr/local/airflow/jars
      - ./data:/opt/spark-data
    depends_on:
      - spark-master
    networks:
      - airflow

  superset:
    image: superset-custom:latest
    container_name: superset
    environment:
      - SUPERSET_SECRET_KEY=your_secret_key_here
    ports:
      - "8088:8088"
    volumes:
      - superset_home:/app/superset_home
    networks:
      - airflow
    command: >
      /bin/sh -c "
      superset db upgrade &&
      superset fab create-admin --username admin --firstname Admin --lastname User --email admin@superset.com --password admin || true &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088"

  webserver-prod:
    image: etl-airflow_aa9abc/airflow:latest
    build:
      context: .
    environment:
      - ENV=prod
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@host.docker.internal:5432/meta_morph
      - AIRFLOW__CORE__DAGS_FOLDER=/usr/local/airflow/prod_dags
      - AIRFLOW__WEBSERVER__SECRET_KEY=98UaXRJpmpMLQxApaCw9ZA==
    ports:
      - "3600:3600"
    volumes:
      - ./prod_dags:/usr/local/airflow/prod_dags
    networks:
      - airflow
    command: >
      /bin/bash -c "
      rm -rf /tmp/repo &&
      git clone --branch master https://github.com/yateesh-chandra-duggirala/Meta-Morph-ETL-Databricks.git /tmp/repo &&
      cp -r /tmp/repo/ETL-Airflow/dags/* /usr/local/airflow/prod_dags/ &&
      airflow db upgrade &&
      airflow sync-perm &&
      airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin &&
      airflow webserver --port 3600"

  scheduler-prod:
    image: etl-airflow_aa9abc/airflow:latest
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__SCHEDULER__MAX_THREADS=10
      - AIRFLOW__CORE__PARALLELISM=10
      - AIRFLOW__CORE__DAG_CONCURRENCY=10
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@host.docker.internal:5432/meta_morph
      - AIRFLOW__CORE__DAGS_FOLDER=/usr/local/airflow/prod_dags
      - AIRFLOW__WEBSERVER__SECRET_KEY=98UaXRJpmpMLQxApaCw9ZA==
    volumes:
      - ./prod_dags:/usr/local/airflow/prod_dags
    networks:
      - airflow
    command: >
      /bin/bash -c "
      airflow db upgrade &&
      airflow scheduler"

  triggerer-prod:
    image: etl-airflow_aa9abc/airflow:latest
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://postgres:postgres@host.docker.internal:5432/meta_morph
      - AIRFLOW__CORE__DAGS_FOLDER=/usr/local/airflow/prod_dags
      - AIRFLOW__WEBSERVER__SECRET_KEY=98UaXRJpmpMLQxApaCw9ZA==
    volumes:
      - ./prod_dags:/usr/local/airflow/prod_dags
    networks:
      - airflow
    command: >
      /bin/bash -c "
      airflow db upgrade &&
      airflow triggerer"

volumes:
  spark-data:
  superset_home:

networks:
  airflow: